schedules:
- cron: "0 6 * * 1-5"
  displayName: At 06:00 UTC on every day-of-week from Monday through Friday.
  branches:
    include:
    - trunk
  always: true

trigger: none

pool:
  vmImage: "ubuntu-latest"

variables: 
- group: platform-bootstrap

steps:
  - bash: |
      elasticpools=$(curl --show-error --request GET --header "Content-Type: application/json" --user ":$AZDO_PERSONAL_ACCESS_TOKEN" "https://dev.azure.com/3lvia/_apis/distributedtask/elasticpools?api-version=6.1-preview.1")
      poolId=$(jq '.value | .[] | select(.azureId == "/subscriptions/6cd117f2-adb1-452e-a60e-86131c1f11d4/resourceGroups/CORE-RGPROD/providers/Microsoft.Compute/virtualMachineScaleSets/pipelineagent-vmss-prod") | .poolId ' <<< $elasticpools)
      if [ -z $poolId ]
      then
        echo "agent pool elvia not found"
        exit 1
      fi
      curl --show-error --request PATCH --header "Content-Type: application/json" --user ":$AZDO_PERSONAL_ACCESS_TOKEN" --data '{"recycleAfterEachUse":false,"maxSavedNodeCount":0,"maxCapacity":4,"desiredIdle":1,"timeToLiveMinutes":10,"agentInteractiveUI":false}' "https://dev.azure.com/3lvia/_apis/distributedtask/elasticpools/$poolId?api-version=6.1-preview.1" 
    displayName: Scale up elvia agent pool
    env: 
      AZDO_PERSONAL_ACCESS_TOKEN: $(AZDO_PERSONAL_ACCESS_TOKEN)
